import React from 'react'
import { Viewer, Worker } from '@react-pdf-viewer/core'
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout'
import '@react-pdf-viewer/core/lib/styles/index.css'
import '@react-pdf-viewer/default-layout/lib/styles/index.css'
import Head from 'next/head'
import Link from 'next/link'

const Download = () => {
  
  const defaultLayoutPluginInstance = defaultLayoutPlugin()

  return (
    <>
      <Head>
        <title>Download Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="container mx-auto px-4 py-6">
          <div className="flex items-center justify-center font-bold text-stone-800 text-2xl pb-8">
            This is <span className="text-emerald-900 ml-2">DOWNLOADPAGE!</span>
          </div>
          <div>
            <Worker workerUrl="https://unpkg.com/pdfjs-dist/build/pdf.worker.min.js">
              <Viewer 
                fileUrl="/surprise.pdf" 
                plugins={[defaultLayoutPluginInstance]}
              />
            </Worker>
          </div>
        </div>
      </>
    </>
  )
}

export default Download