import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Home/Navbar'
import Hero from '../components/Home/Hero'

import styled from 'styled-components'


const Home = () => {
  return (
    <>
      <Head>
        <title>Binar Car Rental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      <Section>
        <Hero />
      </Section>
    </>
  )
}

const Section = styled.div`
  width: 100%;
  height: 100%;
  padding-top: 70px;
`

export default Home
