import React from 'react'
import Card from '../components/Card/Card'
import Head from 'next/head'

export default function Index() {
  return (
    <div>
      <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;700&family=Rubik:wght@300&display=swap" rel="stylesheet" />
      </Head>
      <div>
        <div className="flex flex-col justify-center items-center mt-7 text-neutral-800 font-main">
            <div className="text-4xl font-bold mb-4">Welcome Student!</div>
            <div className="italic mb-8">create by Next JS</div>
        </div>

        <Card />
      </div>
    </div>
  )
}
